import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)
const compat = new FlatCompat({ baseDirectory: __dirname })

const config = [
  {
    // Lint the application, not the workbench.
    //
    // These are one-off local utilities and leftovers sitting in the project
    // root — CommonJS icon scripts, a scratch DB file, an orphaned component.
    // They are never imported by the app and never reach the bundle, but they
    // produced every one of the 18 lint errors that forced
    // `ignoreDuringBuilds: true`. Excluding them lets lint actually gate the
    // build on code that ships.
    //
    // next-env.d.ts is generated by Next on every build and its triple-slash
    // reference is required, so it cannot be "fixed".
    ignores: [
      'find-icons.js',
      'fix-image-icon.js',
      'generate-icons.js',
      'replace-icons.js',
      'scratch_db.js',
      'seed-footer.js',
      'db.ts',
      'old_hero.tsx',
      'next-env.d.ts',
      '.next/**',
      'scripts/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  { rules: {
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-unused-vars':  'warn',
    'react/no-unescaped-entities':        'warn',
    '@next/next/no-img-element':          'warn',
  }},
]
export default config
