import { MongoClient } from 'mongodb'

const MONGODB_URI = process.env.MONGODB_URI as string
const MONGODB_DB = process.env.MONGODB_DB as string

if (!MONGODB_URI) {
  throw new Error('Please define the MONGODB_URI environment variable inside .env.local')
}

const shopifyData = {
  slug: 'shopify',
  title: 'Shopify Services',
  status: 'published',
  hero: {
    eyebrow: 'Shopify Services',
    headline: 'Professional Shopify',
    subheadline: 'Development Services',
    desc: 'From startup stores to enterprise Shopify Plus platforms, we create high-converting e-commerce experiences that drive sales. Trusted by 30+ Shopify businesses worldwide.',
    bullets: [
      'Custom Development — Unique stores that stand out',
      'Conversion-Focused — Optimized for maximum sales',
      'Shopify Plus Ready — Enterprise solutions available',
      'Mobile-Optimized — Perfect on every device',
      '24/7 Expert Support — Always here to help'
    ],
    ctaPrimary: 'Get Free Shopify Store Audit',
    ctaSecondary: 'View Shopify Portfolio',
    startingPrice: 'Starting at $999 · 30-Day Money-Back Guarantee · Free Post-Launch Training'
  },
  services: [
    {
      id: 'development',
      title: 'Shopify Store Development',
      tagline: 'Launch Your Dream E-commerce Store',
      price: '$999',
      time: '2–3 weeks',
      desc: 'Transform your business idea into a profitable Shopify store. Our custom development approach creates unique, high-converting stores that capture your brand essence and drive sales from day one.',
      features: [
        'Custom Shopify theme development',
        'Responsive design across all devices',
        'Product catalog setup and optimization',
        'Payment gateway integration (Stripe, PayPal, etc.)',
        'Shipping configuration and tax setup',
        'SEO optimization and structure',
        'Google Analytics and conversion tracking',
        'Social media integration',
        'Customer account setup',
        '30 days of free support',
      ],
      perfectFor: ['New businesses launching online', 'Brands moving from other platforms', 'Companies needing unique, custom designs', 'Entrepreneurs starting their e-commerce journey'],
    },
    {
      id: 'migration',
      title: 'Shopify Migration Services',
      tagline: 'Seamless Migration to Shopify',
      price: '$799',
      time: '1–2 weeks',
      desc: 'Moving your e-commerce store to Shopify? We handle the complete migration process while preserving your SEO rankings, customer data, and sales history. Zero downtime, zero data loss guaranteed.',
      features: [
        'All product data and images transferred',
        'Customer accounts and order history',
        'Blog posts and pages',
        'SEO settings and redirects',
        'Reviews and testimonials',
        'Email subscribers',
        'Analytics tracking setup',
        '30-day post-migration support',
      ],
      supported: ['WooCommerce to Shopify', 'Magento to Shopify', 'BigCommerce to Shopify', 'Custom platforms to Shopify', 'Other e-commerce platforms'],
      perfectFor: ['Brands moving from WooCommerce or Magento', 'Businesses wanting easier store management', 'Stores seeking faster growth on Shopify'],
    },
    {
      id: 'performance',
      title: 'Shopify Performance Optimization',
      tagline: 'Maximize Your Store\'s Speed and Conversions',
      price: '$599',
      time: '5–7 days',
      desc: 'Slow Shopify stores lose customers and sales. Our performance optimization service can improve your store speed by 40–60%, leading to higher conversions and better customer experience.',
      features: [
        'Comprehensive speed audit and analysis',
        'Image optimization and compression',
        'Code optimization and cleanup',
        'App performance review and optimization',
        'Theme speed enhancements',
        'CDN implementation',
        'Mobile speed optimization',
        'Core Web Vitals improvement',
      ],
      results: ['40–60% faster loading times', 'Improved Google PageSpeed scores', '15–25% increase in conversions', 'Reduced bounce rates', 'Better search engine rankings'],
      perfectFor: [],
    },
    {
      id: 'integrations',
      title: 'Shopify Integration Services',
      tagline: 'Connect Your Store with Essential Business Tools',
      price: '$399+',
      time: '3–5 days per integration',
      desc: 'Streamline your operations by integrating your Shopify store with essential business tools and third-party services. Automate workflows and improve efficiency across your entire business.',
      features: [
        'Google Analytics 4 & Facebook Pixel setup',
        'Mailchimp / Klaviyo email marketing integration',
        'ShipStation & inventory management systems',
        'QuickBooks & Xero accounting connection',
        'Facebook Shop & Google Shopping setup',
        'Affiliate & loyalty program integration',
        'API development for custom tools',
        'Custom workflow automation',
      ],
      perfectFor: ['Businesses wanting to automate operations', 'Stores expanding to multichannel selling', 'Companies needing CRM or ERP integration'],
    },
    {
      id: 'maintenance',
      title: 'Shopify Maintenance & Support',
      tagline: 'Keep Your Shopify Store Running Smoothly',
      price: '$99/mo',
      time: 'Ongoing',
      desc: 'Focus on growing your business while we handle the technical aspects. Our comprehensive maintenance service ensures your Shopify store stays updated, secure, and optimized for peak performance.',
      features: [
        'Regular theme and app updates',
        'Security monitoring and protection',
        'Performance monitoring and optimization',
        'Broken link checks and fixes',
        'Product data backup and security',
        'SEO health checks',
        'Bug fixes and troubleshooting',
        'Emergency support availability',
      ],
      perfectFor: [],
      plans: [
        { tier: 'Starter Plan', price: '$99/month', features: ['1 Shopify store', 'Monthly updates & checks', 'Basic performance monitoring', 'Email support', '2 hours of modifications'] },
        { tier: 'Growth Plan', price: '$199/month', features: ['Up to 2 Shopify stores', 'Bi-weekly updates & monitoring', 'Advanced performance optimization', 'Priority email & chat support', '5 hours of modifications', 'Monthly performance reports'] },
        { tier: 'Enterprise Plan', price: '$399/month', features: ['Up to 5 Shopify stores', 'Weekly updates & monitoring', 'Real-time performance tracking', '24/7 priority support', '10 hours of modifications', 'Custom feature development', 'Dedicated account manager'] },
      ],
    },
    {
      id: 'plus',
      title: 'Shopify Plus Development',
      tagline: 'Enterprise E-commerce Solutions with Shopify Plus',
      price: '$2,999',
      time: '4–6 weeks',
      desc: 'Scale your high-volume business with Shopify Plus. We specialize in complex enterprise implementations, custom functionality, and advanced integrations that support rapid growth and global expansion.',
      features: [
        'Custom Theme Development for enterprise brands',
        'Advanced Integrations — ERP, CRM, and custom systems',
        'B2B Functionality — Wholesale portals and pricing tiers',
        'Multi-Store Setup — Manage multiple brands/regions',
        'Custom Apps — Develop exclusive functionality',
        'Performance Optimization for high-traffic volumes',
        'Migration Services — Enterprise-level data migration',
        'Advanced security and compliance',
      ],
      perfectFor: ['High-volume merchants (>1M annual sales)', 'Brands with complex requirements', 'International businesses', 'B2B wholesale operations', 'Multi-brand companies'],
    },
    {
      id: 'redesign',
      title: 'Shopify Store Redesign',
      tagline: 'Transform Your Store for Maximum Conversions',
      price: '$1,499',
      time: '3–4 weeks',
      desc: 'Is your Shopify store underperforming? Our redesign service combines modern design with conversion optimization to create stores that not only look amazing but also drive more sales.',
      features: [
        'Modern, mobile-first design',
        'Conversion rate optimization',
        'User experience improvements',
        'Page speed optimization',
        'SEO structure enhancement',
        'Product page optimization',
        'Checkout process improvement',
        '30 days of support',
      ],
      results: ['20–40% increase in conversions', 'Improved mobile experience', 'Better brand representation', 'Higher average order value'],
      perfectFor: ['Stores with outdated designs', 'Businesses with low conversion rates', 'Brands needing a fresh, modern look'],
    },
    {
      id: 'app-dev',
      title: 'Shopify App Development',
      tagline: 'Custom Apps for Unique Business Needs',
      price: '$1,999',
      time: '4–8 weeks',
      desc: 'Need functionality that doesn\'t exist? We develop custom Shopify apps tailored to your specific requirements, giving you competitive advantages and streamlined operations.',
      features: [
        'Public Apps — For the Shopify App Store',
        'Private Apps — Exclusive to your store',
        'Custom product configurators',
        'Subscription and recurring billing systems',
        'Loyalty and rewards programs',
        'Advanced search and filtering',
        'B2B pricing and catalogs',
        'Multi-vendor marketplaces',
      ],
      perfectFor: ['Businesses needing unique functionality', 'Stores wanting automation tools', 'Brands wanting competitive app-based features'],
    },
  ],
  whyUs: [
    { icon: '🏆', title: 'Shopify Partner Excellence', desc: 'Official Shopify Partners with proven expertise in building successful e-commerce stores across various industries.' },
    { icon: '💰', title: 'Conversion-Focused Approach', desc: 'Every store we build is optimized for sales with proven conversion tactics and user experience best practices.' },
    { icon: '🚀', title: 'Shopify Plus Ready', desc: 'Specialized expertise in enterprise-level Shopify Plus implementations for high-growth businesses.' },
    { icon: '📱', title: 'Mobile-Commerce Experts', desc: 'Deep understanding of mobile shopping behaviors ensures your store performs perfectly on all devices.' },
    { icon: '🔧', title: 'Ongoing Partnership', desc: "We're your long-term Shopify growth partner, supporting your business at every stage of expansion." },
    { icon: '⚡', title: 'Performance Obsessed', desc: 'Every Shopify store we develop loads fast and ranks well in search engines.' },
  ],
  process: [],
  portfolio: [
    { name: 'WYOX Sports', industry: 'Sports Equipment (USA)', challenge: 'Complex product variations and US market requirements', solution: 'Custom Shopify store with advanced filtering and checkout optimization', result: '250%', resultLabel: 'increase in online sales' },
    { name: 'Genovie', industry: 'Fashion & Lifestyle', challenge: 'High-end brand representation with seamless UX', solution: 'Custom Shopify Plus store with advanced personalization', result: '180%', resultLabel: 'increase in average order value' },
    { name: 'Janya.pk', industry: 'Wholesale Fashion', challenge: 'B2B wholesale functionality with complex pricing', solution: 'Shopify Plus with custom wholesale portal integration', result: '300%', resultLabel: 'increase in wholesale orders' },
  ],
  faqs: [
    { q: 'How long does it take to build a Shopify store?', a: 'Most custom Shopify stores are completed within 2–4 weeks, while Shopify Plus projects typically take 4–6 weeks depending on complexity.' },
    { q: 'Can you migrate my existing store to Shopify?', a: "Yes! We provide complete migration services from all major e-commerce platforms including WooCommerce, Magento, BigCommerce, and custom solutions." },
    { q: 'Do you provide Shopify hosting?', a: 'Shopify includes hosting as part of their platform. We help with setup, optimization, and ongoing management of your Shopify store.' },
    { q: "What's included in the post-launch support?", a: 'All Shopify projects include 30 days of free support covering bug fixes, minor adjustments, training, and guidance on store management.' },
    { q: 'Can you help with Shopify marketing and SEO?', a: 'While we focus on development, we include basic SEO optimization and can recommend trusted partners for advanced marketing services.' },
    { q: 'How much does Shopify maintenance cost?', a: 'Our Shopify maintenance plans start at $99/month and include updates, monitoring, support, and monthly modifications.' },
    { q: 'Do you work with Shopify Plus?', a: "Yes! We're experienced with Shopify Plus implementations for enterprise clients requiring advanced features and higher transaction volumes." },
    { q: 'Can you develop custom Shopify apps?', a: 'Absolutely! We develop both private apps for individual stores and public apps for the Shopify App Store.' },
  ],
  seo: {
    title: 'Professional Shopify Development Services | Ariosetech',
    description: 'Scale Your E-commerce Business with Expert Shopify Solutions. We create high-converting e-commerce experiences that drive sales.',
  }
}

const wordpressData = {
  slug: 'wordpress',
  title: 'WordPress Services',
  status: 'published',
  hero: {
    eyebrow: 'WordPress Services',
    headline: 'Professional WordPress',
    subheadline: 'Development Services',
    desc: 'From simple business websites to complex enterprise platforms, we create WordPress sites that drive results. Trusted by 50+ businesses worldwide for speed, security, and scalability.',
    bullets: [
      'Custom Development — Tailored to your exact needs',
      'Lightning Fast — Optimized for Core Web Vitals',
      '100% Secure — Enterprise-grade security',
      'SEO-Ready — Built for search engine success',
      '24/7 Support — Always here when you need us'
    ],
    ctaPrimary: 'Get Free WordPress Consultation',
    ctaSecondary: 'View WordPress Portfolio',
    startingPrice: 'Starting at $799 · 30-Day Money-Back Guarantee · Free Post-Launch Support'
  },
  services: [
    {
      id: 'development',
      title: 'WordPress Website Development',
      tagline: 'Build Your Dream Website from Scratch',
      price: '$799',
      time: '2–3 weeks',
      desc: 'Transform your vision into a stunning, high-performing WordPress website. Our custom development approach ensures your site stands out from the competition while delivering exceptional user experience.',
      features: ['Custom theme development from your designs', 'Responsive design across all devices', 'SEO-optimized structure and content', 'Contact forms and lead generation tools', 'Social media integration', 'Google Analytics setup', 'Basic on-page SEO optimization', '30 days of free support'],
      perfectFor: ['New businesses launching online', 'Companies needing complete website overhaul', 'Brands requiring unique, custom designs', 'Businesses with specific functionality requirements'],
    },
    {
      id: 'migration',
      title: 'WordPress Migration Services',
      tagline: 'Seamless Migration Without Downtime',
      price: '$299',
      time: '3–5 days',
      desc: 'Moving to WordPress or changing hosts? We handle the entire migration process while ensuring zero data loss and minimal downtime. Your SEO rankings and user experience remain intact.',
      features: ['Complete site backup and migration', 'Domain and hosting setup assistance', 'SSL certificate installation', 'Email migration (if required)', 'Speed and performance optimization', 'SEO preservation techniques', 'Testing across all devices', '14 days of post-migration support'],
      perfectFor: ['Sites moving from Wix, Squarespace, etc.', 'WordPress to WordPress migrations', 'Hosting provider changes', 'Development to live site transfers'],
    },
    {
      id: 'bugs',
      title: 'WordPress Bug & Error Fixing',
      tagline: 'Quick Resolution for WordPress Issues',
      price: '$149',
      time: '24–48 hours',
      desc: 'Is your WordPress site showing errors, broken pages, or strange behavior? Our experts diagnose and fix issues quickly, getting your site back to peak performance.',
      features: ['White screen of death & 500 error fixes', 'Database connection error resolution', 'Plugin conflicts and compatibility fixes', 'Theme-related problem solving', 'Broken layouts and design fixes', 'Login and admin access restoration', 'Email functionality fixes', '7 days of post-fix monitoring'],
      perfectFor: ['Sites experiencing sudden errors', 'Businesses losing revenue due to downtime', 'WordPress sites with plugin conflicts', 'Emergency fixes needed urgently'],
    },
    {
      id: 'maintenance',
      title: 'WordPress Maintenance & Support',
      tagline: 'Keep Your WordPress Site Running Smoothly',
      price: '$79/mo',
      time: 'Ongoing',
      desc: 'Regular maintenance is crucial for WordPress security, performance, and reliability. Our comprehensive maintenance plans ensure your site stays updated, secure, and optimized.',
      features: ['WordPress core, theme & plugin updates', 'Security monitoring and malware scans', 'Database optimization and cleanup', 'Broken link checks and fixes', 'Performance monitoring and reporting', 'Regular backups (stored securely)', 'Uptime monitoring', 'Priority support for issues'],
      perfectFor: [],
      plans: [
        { tier: 'Basic Plan', price: '$79/month', features: ['1 WordPress site', 'Monthly updates and backups', 'Basic security monitoring', 'Email support'] },
        { tier: 'Professional Plan', price: '$149/month', features: ['Up to 3 WordPress sites', 'Weekly updates and backups', 'Advanced security features', 'Performance optimization', 'Priority email & chat support'] },
        { tier: 'Enterprise Plan', price: '$299/month', features: ['Up to 10 WordPress sites', 'Real-time monitoring', 'Advanced security & malware removal', 'Speed optimization', '24/7 priority support', 'Monthly performance reports'] },
      ],
    },
    {
      id: 'speed',
      title: 'WordPress Speed Optimization',
      tagline: 'Make Your WordPress Site Lightning Fast',
      price: '$399',
      time: '5–7 days',
      desc: 'Slow websites lose customers and hurt search rankings. Our speed optimization service can improve your site speed by 40–70%, leading to better user experience and higher conversions.',
      features: ['Comprehensive speed audit and analysis', 'Image optimization and compression', 'Caching implementation and configuration', 'Database optimization and cleanup', 'CSS and JavaScript minification', 'CDN setup and configuration', 'Core Web Vitals optimization', 'Mobile speed improvements'],
      results: ['40–70% faster loading times', 'Improved Google PageSpeed scores', 'Better Core Web Vitals', 'Enhanced user experience', 'Higher search engine rankings'],
      perfectFor: [],
    },
    {
      id: 'security',
      title: 'WordPress Security Services',
      tagline: 'Protect Your WordPress Site from Threats',
      price: '$299',
      time: '3–5 days',
      desc: 'WordPress security is not optional. Our comprehensive security service protects your site from hackers, malware, and other threats while ensuring compliance with security best practices.',
      features: ['Malware scanning and removal', 'Firewall installation and configuration', 'Security plugin setup and optimization', 'Login security enhancements', 'File permission optimization', 'Database security improvements', 'SSL certificate installation', 'Security headers implementation'],
      perfectFor: ['E-commerce websites', 'Sites handling sensitive data', 'Businesses requiring compliance', 'Sites previously hacked', 'High-traffic WordPress sites'],
    },
    {
      id: 'virus-removal',
      title: 'WordPress Virus Removal',
      tagline: 'Fast and Complete Malware Removal',
      price: '$199',
      time: '24–48 hours',
      desc: 'Is your WordPress site infected with malware or viruses? We provide emergency malware removal services to get your site clean and secure quickly.',
      features: ['Complete malware scan and removal', 'Infected file cleaning or replacement', 'Database cleanup and optimization', 'Security plugin installation', 'Firewall configuration', 'Google Safe Browsing removal', 'Security recommendations', '30-day monitoring period'],
      perfectFor: ['Sites flagged by Google as dangerous', 'Hacked WordPress websites', 'Sites with unknown malware', 'Emergency malware removal'],
    },
    {
      id: 'backup',
      title: 'WordPress Backup Solutions',
      tagline: 'Never Lose Your WordPress Data Again',
      price: '$29/mo',
      time: 'Ongoing',
      desc: 'Protect your valuable content and data with automated, reliable backup solutions. Our backup service ensures you can restore your site quickly in case of any emergency.',
      features: ['Automated daily backups', 'Multiple backup storage locations', 'One-click restore functionality', 'Database and file backups', 'Incremental backup options', 'Encrypted secure storage', 'Easy backup management', 'Email notifications'],
      perfectFor: [],
      plans: [
        { tier: 'Basic Backup', price: '$29/month', features: ['Daily automated backups', '30-day backup retention', 'One-click restore', 'Email notifications'] },
        { tier: 'Advanced Backup', price: '$59/month', features: ['Real-time backups', '90-day backup retention', 'Multiple restore points', 'Priority restoration support', 'Multiple storage locations'] },
        { tier: 'Enterprise Backup', price: '$99/month', features: ['Continuous backups', '1-year backup retention', 'Instant recovery options', 'Dedicated backup support', 'Custom backup schedules'] },
      ],
    },
    {
      id: 'redesign',
      title: 'WordPress Website Redesign',
      tagline: 'Give Your WordPress Site a Fresh New Look',
      price: '$1,299',
      time: '3–4 weeks',
      desc: 'Is your WordPress site looking outdated? Our redesign service transforms your existing site with modern design, improved functionality, and a better user experience.',
      features: ['Modern, responsive design', 'Improved user experience', 'SEO optimization & speed improvement', 'Mobile-first approach', 'Content migration', 'Competitor analysis included', 'User experience audit', '30 days of support'],
      perfectFor: ['Businesses with outdated websites', 'Companies wanting better conversions', 'Brands needing a modern refresh', 'Sites with poor mobile experience'],
    },
    {
      id: 'multilingual',
      title: 'WordPress Multilingual Websites',
      tagline: 'Reach Global Audiences with Multilingual WordPress',
      price: '$899',
      time: '2–3 weeks',
      desc: 'Expand your business globally with professionally developed multilingual WordPress websites. We create seamless multi-language experiences that engage international audiences.',
      features: ['Multiple language setup and configuration', 'Professional translation management', 'SEO optimization for each language', 'Currency switcher integration', 'Language-specific content management', 'Automatic language detection', 'Multilingual menu and navigation', 'International SEO setup'],
      perfectFor: ['International businesses', 'E-commerce stores selling globally', 'Service providers with global clientele', 'Organizations serving diverse communities'],
    },
  ],
  whyUs: [
    { icon: 'svg_expertise', title: '7+ Years WordPress Expertise', desc: "We've been perfecting WordPress development since 2017, delivering 50+ successful WordPress projects across various industries." },
    { icon: 'svg_performance', title: 'Performance-First Approach', desc: 'Every WordPress site we build is optimized for speed, security, and search engines from day one.' },
    { icon: 'svg_security', title: 'Security-Focused Development', desc: 'We implement enterprise-grade security measures to protect your WordPress site from threats.' },
    { icon: 'svg_mobile', title: 'Mobile-First Design', desc: 'All our WordPress sites are built with mobile users in mind, ensuring perfect performance across all devices.' },
    { icon: 'svg_support', title: 'Ongoing Support', desc: "We don't just build and leave. Our team provides continuous support to ensure your WordPress site thrives." },
    { icon: 'svg_pricing', title: 'Transparent Pricing', desc: 'No hidden costs or surprise fees. Our WordPress development pricing is upfront and honest.' },
  ],
  process: [
    { n: '01', title: 'Discovery & Planning', sub: 'Understand Your Vision', desc: 'Detailed requirement analysis, technical specifications, design wireframes, and project timeline.', time: '2–3 days' },
    { n: '02', title: 'Design & Development', sub: 'Blueprint for Success', desc: 'Custom theme creation, functionality development, responsive design, and content integration.', time: '1–2 weeks' },
    { n: '03', title: 'Testing & Optimization', sub: 'Ensuring Perfection', desc: 'Cross-browser testing, mobile responsiveness check, speed optimization, and security testing.', time: '3–5 days' },
    { n: '04', title: 'Launch & Support', sub: 'Your Success, Our Priority', desc: 'Live deployment, training session, 30-day support period, and maintenance planning.', time: 'Ongoing' },
  ],
  portfolio: [
    { name: '', industry: 'Professional Services', challenge: 'Modern design with complex functionality', solution: 'Custom WordPress theme with advanced features', result: '200%', resultLabel: 'increase in lead generation' },
    { name: '', industry: 'Retail', challenge: 'WordPress with e-commerce functionality', solution: 'WooCommerce integration with custom features', result: '150%', resultLabel: 'increase in online sales' },
    { name: '', industry: 'International Business', challenge: '5-language website with complex navigation', solution: 'WPML-powered multilingual WordPress site', result: '300%', resultLabel: 'increase in international inquiries' },
  ],
  faqs: [
    { q: 'How long does WordPress development take?', a: 'Most WordPress projects are completed within 2–4 weeks, depending on complexity and requirements.' },
    { q: 'Do you provide WordPress hosting?', a: 'We can recommend reliable hosting providers and assist with setup, but we focus on development rather than hosting services.' },
    { q: 'Can you work with existing WordPress sites?', a: 'Absolutely! We provide maintenance, optimization, and enhancement services for existing WordPress websites.' },
    { q: "What's included in post-launch support?", a: 'All WordPress projects include 30 days of free support covering bug fixes, minor adjustments, and training.' },
    { q: 'Do you use WordPress page builders?', a: 'We prefer custom development for better performance, but can work with page builders like Elementor or Gutenberg when requested.' },
    { q: 'How much does WordPress maintenance cost?', a: 'Our maintenance plans start at $79/month and include updates, backups, security monitoring, and support.' },
  ],
  seo: {
    title: 'Professional WordPress Development Services | Ariosetech',
    description: 'From simple business websites to complex enterprise platforms, we create WordPress sites that drive results.',
  }
}

const woocommerceData = {
  slug: 'woocommerce',
  title: 'WooCommerce Services',
  status: 'published',
  hero: {
    eyebrow: 'WooCommerce Services',
    headline: 'Custom WooCommerce',
    subheadline: 'Development Services',
    desc: 'Transform your WordPress site into a powerful online store that drives sales. We create custom WooCommerce solutions that combine the flexibility of WordPress with robust e-commerce functionality. Trusted by 40+ businesses worldwide.',
    bullets: [
      'Custom Development — Tailored to your exact needs',
      'WordPress Integration — Seamless blend of content and commerce',
      'Scalable Solutions — Grow from startup to enterprise',
      'Mobile-Optimized — Perfect shopping experience on all devices',
      '24/7 Expert Support — Always here when you need us'
    ],
    ctaPrimary: 'Get Free WooCommerce Consultation',
    ctaSecondary: 'View WooCommerce Portfolio',
    startingPrice: 'Starting at $1,299 · 30-Day Money-Back Guarantee · Free Post-Launch Training'
  },
  services: [
    {
      id: 'development',
      title: 'WooCommerce Website Development',
      tagline: 'Launch Your Ultimate E-commerce Store',
      price: '$1,299',
      time: '3–4 weeks',
      desc: 'Build a powerful online store that leverages the best of WordPress and WooCommerce. Our custom development creates unique, high-converting stores that perfectly match your brand and business requirements.',
      features: [
        'Custom WooCommerce theme development',
        'Responsive design across all devices',
        'Complete product catalog setup',
        'Payment gateway integration (Stripe, PayPal, Bank transfers)',
        'Shipping zones and tax configuration',
        'Inventory management system',
        'Customer account functionality',
        'Order management and tracking',
        'SEO optimization for products and pages',
        'Google Analytics and conversion tracking',
        'Email automation setup',
        '30 days of free support',
      ],
      perfectFor: ['Businesses wanting WordPress + e-commerce', 'Companies needing content marketing integration', 'Brands requiring extensive customization', 'Businesses planning to scale significantly'],
    },
    {
      id: 'theme',
      title: 'WooCommerce Theme Customization',
      tagline: 'Transform Your Store with Custom Design',
      price: '$899',
      time: '2–3 weeks',
      desc: 'Make your WooCommerce store stand out with completely custom theme development or extensive customization of existing themes. We create unique shopping experiences that reflect your brand and drive conversions.',
      features: [
        'Complete theme redesign and development',
        'Custom homepage and product page layouts',
        'Brand-specific color schemes and typography',
        'Custom icons and graphics integration',
        'Advanced product display options',
        'Custom checkout process design',
        'Mobile-first responsive design',
        'Speed and performance optimization',
      ],
      perfectFor: ['Stores wanting unique brand representation', 'Businesses with existing WooCommerce sites', 'Companies needing design improvements', 'Brands wanting to improve conversions'],
    },
    {
      id: 'payments',
      title: 'WooCommerce Payment Gateway Integration',
      tagline: 'Secure, Seamless Payment Processing',
      price: '$299/gateway',
      time: '3–5 days',
      desc: 'Offer your customers the payment methods they prefer with secure, reliable payment gateway integrations. We implement and optimize payment systems that reduce cart abandonment and increase conversions.',
      features: [
        'Stripe (credit cards, digital wallets)',
        'PayPal (Standard, Pro, Express Checkout)',
        'Apple Pay and Google Pay',
        'Razorpay, Paytm & international gateways',
        'PCI DSS compliance assistance',
        'SSL certificate implementation',
        'Fraud protection setup',
        '3D Secure authentication',
      ],
      perfectFor: ['Stores expanding payment options', 'International e-commerce businesses', 'Companies wanting to reduce cart abandonment', 'Stores targeting mobile customers'],
    },
    {
      id: 'performance',
      title: 'WooCommerce Performance Optimization',
      tagline: 'Maximize Speed, Sales, and Search Rankings',
      price: '$699',
      time: '5–7 days',
      desc: 'Slow e-commerce sites lose customers and sales. Our comprehensive optimization service can improve your WooCommerce store speed by 50–70%, leading to higher conversions, better user experience, and improved search rankings.',
      features: [
        'Database query optimization',
        'Image compression and optimization',
        'Caching implementation (page, object, browser)',
        'CDN setup and configuration',
        'Server-level optimizations',
        'Plugin performance review',
        'Checkout process speedup',
        'Mobile-first performance tuning',
      ],
      results: ['50–70% faster loading times', 'Improved Google PageSpeed scores (90+)', 'Better Core Web Vitals', '20–35% increase in conversions', 'Reduced bounce rates', 'Higher search engine rankings'],
      perfectFor: [],
    },
    {
      id: 'maintenance',
      title: 'WooCommerce Maintenance & Support',
      tagline: 'Keep Your Store Running Smoothly',
      price: '$129/mo',
      time: 'Ongoing',
      desc: 'Focus on growing your business while we handle the technical aspects. Our comprehensive maintenance service ensures your WooCommerce store stays updated, secure, and optimized for peak performance.',
      features: [
        'WordPress and WooCommerce core updates',
        'Plugin and theme updates',
        'Security monitoring and hardening',
        'Performance monitoring and optimization',
        'Database optimization and cleanup',
        'Inventory monitoring and alerts',
        'Order system monitoring',
        'Backup management and testing',
      ],
      perfectFor: [],
      plans: [
        { tier: 'Essential Plan', price: '$129/month', features: ['1 WooCommerce store', 'Monthly updates & security checks', 'Basic performance monitoring', 'Email support (48-hour response)', '2 hours of modifications', 'Monthly backup verification'] },
        { tier: 'Professional Plan', price: '$249/month', features: ['Up to 2 WooCommerce stores', 'Bi-weekly updates & monitoring', 'Advanced security features', 'Priority support (24-hour response)', '5 hours of modifications', 'Weekly backup management', 'Monthly performance reports'] },
        { tier: 'Enterprise Plan', price: '$499/month', features: ['Up to 5 WooCommerce stores', 'Weekly updates & monitoring', 'Real-time security monitoring', '24/7 priority support', '10 hours of modifications', 'Daily backup management', 'Custom feature development', 'Dedicated account manager'] },
      ],
    },
    {
      id: 'multivendor',
      title: 'WooCommerce Multi-vendor Solutions',
      tagline: 'Create Your Own E-commerce Marketplace',
      price: '$1,999',
      time: '4–6 weeks',
      desc: 'Transform your WooCommerce store into a thriving multi-vendor marketplace where multiple sellers can list and sell their products. Perfect for creating Amazon-like platforms or expanding your business model.',
      features: [
        'Vendor registration and approval system',
        'Individual vendor dashboards',
        'Commission management system',
        'Payment splitting and payouts',
        'Vendor ratings and reviews',
        'Advanced search and filtering',
        'Single checkout for multiple vendors',
        'Admin management dashboard',
        'Mobile-optimized vendor interface',
        '30 days of marketplace support',
      ],
      perfectFor: ['Entrepreneurs creating marketplaces', 'Businesses wanting to expand product range', 'Companies with multiple suppliers', 'Platforms connecting buyers and sellers'],
    },
    {
      id: 'multilingual',
      title: 'WooCommerce Multilingual Websites',
      tagline: 'Expand Globally with Multilingual E-commerce',
      price: '$1,499',
      time: '3–4 weeks',
      desc: 'Reach international customers with professionally developed multilingual WooCommerce stores. We create seamless multi-language shopping experiences that engage global audiences and drive international sales.',
      features: [
        'Multiple language setup (unlimited languages)',
        'Professional translation workflow',
        'Language switcher integration',
        'Automatic language detection',
        'RTL (right-to-left) language support',
        'Multi-currency and automatic conversion',
        'Location-based pricing',
        'Country-specific payment methods',
        'Translated product catalogs',
        'International SEO configuration',
      ],
      perfectFor: ['Stores expanding internationally', 'Businesses targeting specific regions', 'Companies with multilingual customers', 'Global brands launching online'],
    },
    {
      id: 'migration',
      title: 'WooCommerce Migration Services',
      tagline: 'Seamless Migration to WooCommerce',
      price: '$999',
      time: '1–3 weeks',
      desc: 'Moving your e-commerce store to WooCommerce? We handle the complete migration process while preserving your SEO rankings, customer data, order history, and ensuring zero downtime.',
      features: [
        'Product catalog with all variations and attributes',
        'Customer accounts and order history',
        'Reviews and testimonials',
        'Blog posts and content pages',
        'SEO settings and URL redirects',
        'Payment and shipping configurations',
        'Email subscribers and marketing lists',
        'Analytics tracking setup',
        '30-day dedicated post-migration support',
      ],
      supported: ['Shopify to WooCommerce', 'Magento to WooCommerce', 'OpenCart to WooCommerce', 'PrestaShop to WooCommerce', 'BigCommerce to WooCommerce', 'Custom Platforms'],
      perfectFor: ['Stores wanting lower ongoing costs', 'Businesses needing complete customization freedom', 'Stores wanting better SEO control'],
    },
  ],
  whyUs: [
    { icon: '🏆', title: 'WordPress + WooCommerce Expertise', desc: 'Deep understanding of both WordPress and WooCommerce ensures seamless integration and optimal performance for your online store.' },
    { icon: '🛒', title: 'E-commerce Focus', desc: 'Specialized in e-commerce development with proven strategies for increasing conversions, average order value, and customer retention.' },
    { icon: '🎨', title: 'Custom Solutions', desc: 'Every WooCommerce store we build is uniquely tailored to your business needs, brand identity, and growth objectives.' },
    { icon: '⚡', title: 'Performance Obsessed', desc: 'We optimize every aspect of your store for speed, ensuring fast loading times that keep customers engaged and improve search rankings.' },
    { icon: '🔒', title: 'Security First', desc: 'Enterprise-grade security measures protect your store and customer data from threats, ensuring trust and compliance.' },
    { icon: '📈', title: 'Growth Partnership', desc: "We don't just build stores; we create growth-focused solutions that scale with your business and support long-term success." },
  ],
  process: [],
  portfolio: [
    { name: 'The Kapra', industry: 'Fashion E-commerce', challenge: 'Complex inventory management and custom features', solution: 'Custom WooCommerce with advanced product variations', result: '300%', resultLabel: 'increase in online sales' },
    { name: 'Dr. Scents International', industry: 'Perfume & Cosmetics', challenge: '32 different country-specific websites', solution: 'Multi-site WooCommerce with localization', result: '32', resultLabel: 'countries launched in under 4 months' },
    { name: 'GeoMag World', industry: 'Educational Toys', challenge: 'Complex product catalog with learning resources', solution: 'WooCommerce with custom product configurator', result: '200%', resultLabel: 'increase in average order value' },
  ],
  faqs: [
    { q: 'How much does a WooCommerce store cost?', a: 'Custom WooCommerce development starts at $1,299 for basic stores. Complex stores with advanced features range from $2,000–$5,000+. We provide detailed quotes based on your specific requirements.' },
    { q: 'How long does WooCommerce development take?', a: 'Most custom WooCommerce stores are completed within 3–5 weeks. Complex stores with extensive customization may take 6–8 weeks. We provide realistic timelines during consultation.' },
    { q: 'Can you migrate my existing store to WooCommerce?', a: 'Yes! We provide complete migration services from Shopify, Magento, and other platforms. Migration typically takes 1–3 weeks depending on store complexity.' },
    { q: 'Is WooCommerce better than Shopify?', a: 'WooCommerce offers more customization freedom and lower long-term costs, while Shopify provides easier management. We help you choose based on your specific needs.' },
    { q: 'Do you provide WooCommerce hosting?', a: 'We recommend reliable WordPress hosting providers and assist with setup and optimization. We focus on development while partnering with trusted hosting companies.' },
    { q: "What's included in post-launch support?", a: 'All WooCommerce projects include 30 days of free support covering bug fixes, minor adjustments, training, and guidance on store management.' },
    { q: 'Can WooCommerce handle large product catalogs?', a: 'Absolutely! WooCommerce can handle thousands of products when properly optimized. We implement performance optimizations for large-scale e-commerce operations.' },
    { q: 'Do you develop custom WooCommerce plugins?', a: "Yes! We develop custom plugins and extensions to add unique functionality to your WooCommerce store that isn't available in existing plugins." },
  ],
  seo: {
    title: 'Custom WooCommerce Development Services | Ariosetech',
    description: 'Transform your WordPress site into a powerful online store that drives sales with our expert WooCommerce solutions.',
  }
}

const seoData = {
  slug: 'seo',
  title: 'SEO Services',
  status: 'published',
  hero: {
    eyebrow: 'SEO Services',
    headline: 'SEO Services That Help',
    subheadline: 'Your Business Get Found',
    desc: 'Ariosetech helps businesses grow through strategic SEO built around visibility, traffic, leads, and long-term digital performance. From technical fixes to local SEO and content strategy, we build a stronger search presence that supports real business growth.',
    bullets: [],
    ctaPrimary: 'Book a Free SEO Consultation',
    ctaSecondary: 'Get a Website Audit',
  },
  services: [
    {
      id: 'website-seo',
      title: 'Website SEO',
      tagline: 'Website SEO That Strengthens Your Foundation',
      price: '',
      time: '',
      desc: 'We improve the on-page SEO and structural setup of your website so search engines can better understand your content and users can move through your site more clearly. This includes heading structure, metadata, content optimization, internal linking, page targeting, keyword mapping, and overall SEO alignment.',
      features: [
        'On-page SEO improvements',
        'Page-level optimization',
        'Heading and content structure',
        'Metadata optimization',
        'Internal linking strategy',
        'Keyword targeting and mapping',
      ],
    },
    {
      id: 'local-seo',
      title: 'Local SEO',
      tagline: 'Local SEO That Brings More Calls and Leads',
      price: '',
      time: '',
      desc: 'For local businesses, visibility in your service areas matters. We help improve your local presence through Google Business Profile optimization, local landing pages, service-area targeting, on-page local signals, and stronger geographic relevance across your website.',
      features: [
        'Google Business Profile optimization',
        'Local keyword targeting',
        'City and service-area pages',
        'Local on-page SEO',
        'Location-based content support',
        'Better visibility for local intent searches',
      ],
    },
    {
      id: 'technical-seo',
      title: 'Technical SEO',
      tagline: 'Technical SEO That Fixes What Holds You Back',
      price: '',
      time: '',
      desc: 'Many websites struggle to rank because of technical problems happening behind the scenes. We identify and fix issues related to crawlability, indexing, site speed, mobile usability, page structure, duplicates, and weak internal architecture so your website performs better in search.',
      features: [
        'Technical SEO audits',
        'Crawl and indexing fixes',
        'Page speed improvement recommendations',
        'Mobile usability checks',
        'Site structure improvements',
        'Duplicate and thin content review',
      ],
    },
    {
      id: 'seo-content',
      title: 'SEO Content',
      tagline: 'SEO Content That Builds Topical Strength',
      price: '',
      time: '',
      desc: 'We help businesses create and improve content that supports rankings, search intent, and topical authority. This includes service page optimization, blog strategy, content planning, keyword clustering, and search-focused content improvements that help your site compete more effectively.',
      features: [
        'SEO content strategy',
        'Service page optimization',
        'Blog topic planning',
        'Keyword clustering',
        'Content updates and refreshes',
        'Content structure for search intent',
      ],
    },
  ],
  whyUs: [
    { icon: '🎯', title: 'Business-First SEO', desc: 'We focus on visibility that supports real business outcomes, not just traffic numbers.' },
    { icon: '⚙️', title: 'Development and SEO in Sync', desc: 'Because our team works across websites, structure, and performance, we can align SEO with how your site is actually built.' },
    { icon: '✅', title: 'Clean, Practical Execution', desc: 'We focus on the changes that make the biggest impact without creating confusion or unnecessary complexity.' },
    { icon: '📈', title: 'Long-Term Growth Thinking', desc: 'We build SEO in a way that supports stronger performance over time, not just short-term spikes.' },
    { icon: '🏪', title: 'Support for Different Business Types', desc: 'We work with service businesses, local brands, and eCommerce companies that need stronger digital visibility.' },
  ],
  process: [
    { n: '01', title: 'Audit', sub: '', desc: 'We review your website, search presence, content, and technical condition to understand what is holding performance back.', time: '' },
    { n: '02', title: 'Strategy', sub: '', desc: 'We build an SEO plan based on your business model, audience, goals, and search opportunities.', time: '' },
    { n: '03', title: 'Optimization', sub: '', desc: 'We improve your pages, structure, technical setup, content targeting, and internal SEO foundation.', time: '' },
    { n: '04', title: 'Content & Growth', sub: '', desc: 'Where needed, we build supporting content, improve weak pages, and strengthen site-wide relevance.', time: '' },
    { n: '05', title: 'Ongoing Improvement', sub: '', desc: 'SEO is not static. We continue refining based on performance, search trends, and growth priorities.', time: '' },
  ],
  portfolio: [],
  faqs: [
    { q: 'What SEO services does Ariosetech offer?',    a: 'We offer website SEO, local SEO, technical SEO, and SEO content support. This includes on-page optimization, technical fixes, local search improvements, and content strategy built to improve rankings and business visibility.' },
    { q: 'Is SEO worth it for small businesses?',       a: 'Yes. SEO helps small businesses show up when potential customers are actively searching for their services. It can improve visibility, bring qualified traffic, and support long-term growth without depending only on paid ads.' },
    { q: 'How long does SEO take to show results?',     a: 'SEO usually takes time because rankings depend on competition, website condition, content quality, and technical setup. Some improvements can be seen earlier, but strong SEO results usually build over months, not days.' },
    { q: 'Do you offer local SEO services?',            a: 'Yes. We help local businesses improve visibility through Google Business Profile optimization, service-area targeting, local page structure, and stronger on-page local signals.' },
    { q: 'Can you fix technical SEO issues on my website?', a: 'Yes. We can review and improve crawl issues, indexing problems, speed-related blockers, mobile usability, internal structure, and other technical factors affecting search performance.' },
    { q: 'Do you also help with SEO content?',          a: "Yes. We help with service page optimization, blog planning, keyword clustering, content updates, and search-focused content strategy to strengthen your site's topical coverage." },
  ],
  seo: {
    title: 'Professional SEO Services | Ariosetech',
    description: 'Ariosetech helps businesses grow through strategic SEO built around visibility, traffic, leads, and long-term digital performance.',
  }
}

async function seedServices() {
  const client = new MongoClient(MONGODB_URI)

  try {
    console.log('Connecting to MongoDB...')
    await client.connect()
    const db = client.db(MONGODB_DB)
    const servicesCol = db.collection('services')

    console.log('Upserting Service Pages...')
    
    const pages = [shopifyData, wordpressData, woocommerceData, seoData]
    
    for (const page of pages) {
      const result = await servicesCol.updateOne(
        { slug: page.slug },
        { $set: { ...page, updatedAt: new Date() } },
        { upsert: true }
      )
      console.log(`- ${page.slug}: ${result.upsertedId ? 'Created' : 'Updated'}`)
    }

    console.log('Services seeded successfully!')
  } catch (error) {
    console.error('Seeding failed:', error)
  } finally {
    await client.close()
  }
}

seedServices()
